import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../../components/headers/Navbar";
import "./globals.css";
import { ThemeProvider } from "../../components/ui/theme-provider"
import Footer from "../../components/footer/footer";
import Providers from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KnowMo",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
          <ThemeProvider>
        <Providers>
            <Navbar/>
            {children}
            <Footer/>
        </Providers>
          </ThemeProvider>
      </body>
    </html>
  );
}
